### PR TITLE
build: lint the commit subject that squash merges will create

### PR DESCRIPTION
**Pull request by IvanStepanok**
#667 grandfathered six commit subjects on `develop` so release pull requests could go green. That treated the symptom. This closes the door they came through, so the list never needs a seventh entry.

## Cause

`.github/workflows/commitlint.yml` calls the shared `openedx/.github` workflow, which runs `wagoid/commitlint-github-action`. That action lints **the commits on the pull request branch**. Those commits are not what lands on `develop`.

This repo squash-merges, and `squash_merge_commit_title` is `COMMIT_OR_PR_TITLE`. GitHub composes the subject as:

- the **pull request title**, when the branch has more than one commit;
- the **head commit's own subject**, when the branch has exactly one;

then appends `` (#N) ``. Nothing lints that composed string. The branch commits pass, the pull request merges, and the release pull request is the first place the real subject is ever checked — by which point it is immutable history.

Both halves are observable in this repo. These four all had exactly one commit, and in every case what landed is the commit subject, not the title:

| PR | Title | Landed on `develop` |
|---|---|---|
| #543 | `fix: Quick Fix colors for Offline Panel` | `chore: delete wrong color (#543)` |
| #629 | `build: fix workflow issues` | ``build: remove `xcodes` installation (#629)`` |
| #588 | `fix: [FC-0078] fetch future course dates for calendar` | `fix: fetch future course dates for calendar (#588)` |
| #537 | `fix: The latest facebook sdk issue` | `fix: decrease facebook sdk version and fix open(url) calling (#537)` |

## What this does

A new workflow composes the same string GitHub will create — branching on the commit count exactly as `COMMIT_OR_PR_TITLE` does — and lints it with the **same `commitlint.config.mjs`**, so one ruleset governs the commits and the subject alike, and the two cannot drift apart.

Verified end to end in a clean checkout with no ancestor `node_modules`:

| Commits | Title | Subject that would land | Exit |
|---|---|---|---|
| 1 | `fix: correct course view padding` | `Update CourseView.swift (#700)` | **1** |
| 3 | `fix: correct course view padding` | `fix: correct course view padding (#700)` | 0 |
| 3 | `Fix/some thing` | `Fix/some thing (#700)` | **1** |
| 3 | `ci: something` | `ci: something (#700)` | **1** |
| 3 | `Fix/issue 581` | `Fix/issue 581 (#635)` | 0 |
| 3 | `Fix/issue 581` | `Fix/issue 581 (#700)` | **1** |

The first row is the case a title-only check reports green on. The last two show #667's grandfather list staying pinned to its exact commits: the same text at a new pull request number is rejected.

## Three details that are load-bearing

**Composing the `` (#N) `` suffix, not linting the bare title.** `header-max-length` is 110, and the config's own comment says it is set there "to account for PR numbers on squash merges". A 110-character title passes on its own and fails at 117 once the suffix is added. Linting the bare title would under-enforce the limit by the width of the suffix — which is how `Fixes:  Assignment thumbnails … (#649)` landed at 114.

**`npm install --no-save`, not `npx --package`.** commitlint resolves `extends` relative to the directory holding the config, so `@commitlint/config-conventional` has to sit beside `commitlint.config.mjs` at the repo root. Installing it through `npx --package` puts it in the npx cache, where the resolver cannot see it, and every run dies with `Cannot find module "@commitlint/config-conventional"` — failing closed on correct titles too. There is no root `package.json`, and `--no-save` writes neither one nor a lockfile, so only `node_modules` is left behind. Versions are pinned to 19.x to match the major that `wagoid/commitlint-github-action@v6.2.1` runs.

**`fetch-depth: 2` with an explicit head SHA.** The default checkout for `pull_request` is the merge ref, whose own subject is `Merge <sha> into <sha>` — never the string we want. Depth 2 brings in both parents so the head commit is readable for the single-commit case.

## Deliberate exclusions

Release pull requests (`develop` → `main`) are skipped. They land as merge commits, whose subject is GitHub's auto-generated `Merge pull request #N from …`, which commitlint ignores by default — so the release title never becomes a linted subject and checking it would be pure friction.

The pull request title is untrusted input. It is passed through `env:` rather than interpolated into the script, and `printf` feeds it to stdin so a subject beginning with `-` arrives as data. Verified inert: `feat: x"; touch /tmp/PWNED; echo "` creates no file. `permissions:` is `contents: read` — the title comes from the event payload, so there is no API call.

`pull_request`, not `pull_request_target`: read-only token, no secrets, and a pull request that edits `commitlint.config.mjs` is validated against its own new config. It does execute the pull request's config JS, but the existing commitlint job already does exactly that, so this adds no new exposure.

## Residual gaps

This does not cover a subject that reaches `develop` without a squash merge — an admin merge, a merge-commit strategy, or a direct push. Those are governed by branch protection rather than by CI, so they are out of scope here.

`edited` is in the trigger list because a title can be changed at any point, including after every other check has gone green.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @IvanStepanok!


This repository is currently maintained by `@openedx/openedx-mobile-maintainers`.


Once you've gone through the following steps feel free to tag them in a comment and let them know that your changes are ready for engineering review.

<details><summary>:radio_button: Get product approval</summary>

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.
</details>

<details><summary>:radio_button: Provide context</summary>

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads
</details>





<details><summary>:radio_button: Get a green build</summary>

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.
</details><details>


---

<details><summary>Where can I find more information?</summary>

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)
</details>

<details><summary>When can I expect my changes to be merged?</summary>

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*
</details>
